buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Use a newer AGP that is compatible with Gradle 9
        classpath 'com.android.tools.build:gradle:8.13.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
